container: seerr
image: ghcr.io/seerr-team/seerr:latest
tag: latest
restart: unless-stopped

ports:
  - "5055:5055"

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Monterrey"

volumes:
  - "/home/docker/seerr/config:/app/config"
  - "/mnt/Media:/Media"
  - "/mnt/Media/Downloads:/downloads"
  - "/mnt/Media/TVShows:/TVShows"
  - "/mnt/Media/MyShows:/MyShows"
  - "/mnt/Media/Movies:/Movies"
  - "/mnt/Media/MyMovies:/MyMovies"
